### PR TITLE
fix(html): use helix-query.yaml instead of helix-index.yaml

### LINKED ISSUE #124: HTML pipeline should use helix-query.yaml
Need to change the following reference:

https://github.com/adobe/helix-index-pipelines/blob/b4b0640c5e11968b90e1285d5bf824ffbf351430/src/html_json.js#L61

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #124 

Additionally, use `nock` to intercept HTTP requests for config and HTML files, instead of switching to a file-based loader in `html_json.js` just for testing.

### CODE REVIEW

File: src/html_json.js [hunk 1]
```diff
@@ -48,66 +46,18 @@ const helpers = {
...
-};
-
 /**
  * Load an index configuration from a git repo.
  *
  * @param {object} params
  * @returns configuration
  */
-async function loadConfigFromRepo(params) {
+async function loadConfig(params) {
```
Comment (tripodsan) [inline src/html_json.js]: why not use `action.downloader` instead ?

File: test/html_json.test.js [hunk 2]
```diff
@@ -13,21 +13,24 @@
 /* eslint-env mocha */
 
 const assert = require('assert');
-const path = require('path');
+const nock = require('nock');
+const { basename, resolve } = require('path');
```
Comment (tripodsan) [inline test/html_json.test.js]: I don't like this style...it the `resolve` quite ambigous and when looking at the code below, you have to lookup what resolve actually does.

File: test/html_json.test.js [hunk 3]
```diff
@@ -36,6 +39,17 @@ describe('HTML Indexing', () => {
 
   before(async () => {
     testRoot = await createTestRoot();
+    nock('https://raw.githubusercontent.com/')
+      .get(/\/helix\/github.com--adobe--helix-index-pipelines\/[^/]+\/helix-query.yaml/)
+      .replyWithFile(200, resolve(specsDir, 'blog', 'helix-query.yaml'))
+      .persist();
```
Comment (tripodsan) [inline test/html_json.test.js]: maybe you should also test a case, where `helix-query.yaml` doesn't exist.

File: test/html_json.test.js (hunk 2 above)
Comment (dominique-pfister) [reply test/html_json.test.js]: Well, it's a test case, and a small one. To me, `basename` and `resolve` in combination with paths (as in  `resolve(specsDir, 'blog', 'helix-query.yaml')`) is rather obvious.

File: src/html_json.js (hunk 1 above)
Comment (dominique-pfister) [reply src/html_json.js]: Right, I didn't notice that I was in a pipeline action. But that code didn't change, it dates back from when `action.downloader` wasn't yet available.

File: test/html_json.test.js (hunk 3 above)
Comment (dominique-pfister) [reply test/html_json.test.js]: It just returns an empty configuration then:
```
logger.error(`Failed to load index configuration from: ${url}`, e);
// config not usable return empty
return {
  indices: [],
};
```

File: test/html_json.test.js (hunk 2 above)
Comment (tripodsan) [reply test/html_json.test.js]: but you had to rename the `resolve` in the promise.... I just think it's not a good style. maybe in this case it's kind of ok, but in general, it's rather confusing, especially when looking at diffs and for people who don't know the code.

File: src/html_json.js (hunk 1 above)
Comment (tripodsan) [reply src/html_json.js]: but you changed so much in this PR.... where as the title says: use `helix-query.yaml instead of...`. for me, that would be a oneliner....

Comment (dominique-pfister) [reply src/html_json.js]: Right, but as the initial comment on that PR says:
> Additionally, use nock to intercept HTTP requests for config and HTML files, instead of switching to a file-based loader in html_json.js just for testing.

After introducing `nock`, I was able to remove the file-based config and html loader (`loadConfigFromFile` and `fetchHTMLFromFile`), so e.g. `loadConfigFromRepo` now just becomes `loadConfig`. The function bodies didn't change.

Comment (tripodsan) [reply src/html_json.js]: but anyways...it might be good to use the downloader now :-) or in a separate PR....
