### PR TITLE
fix(deploy): use WSK_CONFIG_FILE

### LINKED ISSUE #141: Use settings from WSK_CONFIG_FILE
In the `openwhisk-action-builder` a WSK_CONFIG_FILE env variable is already taken into account<sup>1</sup>. Suggest to use that for our deploy script as well:

https://github.com/adobe/helix-index-pipelines/blob/22dba06991e69b6349c6d70c66141d1bf2e31f14/build/deploy.js#L104-L108

<sup>1</sup> https://github.com/adobe/openwhisk-action-builder/commit/629e09f45e73e499dd74215b63fa96e6dc4d9d06

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #141

### CODE REVIEW

File: build/deploy.js [hunk 1]
```diff
@@ -100,10 +102,15 @@ class Deploy {
   }
 
   async init() {
-    this.namespace = process.env.WSK_NAMESPACE || 'helix-index';
+    const wskPropsFile = process.env.WSK_CONFIG_FILE || path.resolve(os.homedir(), '.wskprops');
+    let wskProps = {};
+    if (await fse.pathExists(wskPropsFile)) {
+      wskProps = dotenv.parse(await fse.readFile(wskPropsFile));
+    }
+    this.namespace = process.env.WSK_NAMESPACE || wskProps.NAMESPACE || 'helix-index';
```
Comment (dominique-pfister) [inline build/deploy.js]: Not only takes `WSK_CONFIG_FILE` variable but also a `.wskprops` file into account: not sure, whether this could introduce some new behavior that might be confusing?
